package com.insurance.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents an insurance product/plan that customers can purchase.
 * <p>
 * Each policy belongs to a {@link PolicyType} and defines coverage details,
 * premium amounts, eligibility criteria, and an AI-assigned risk category.
 * The {@code policyNumber} is auto-generated by {@link com.insurance.util.PolicyNumberGenerator}.
 *
 * @author Santhosh
 * @since 1.0
 */
@Entity
@Table(name = "policies")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Policy extends BaseEntity {

    @Column(name = "policy_number", nullable = false, unique = true, length = 20)
    private String policyNumber;

    @NotBlank(message = "Policy name is required")
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @NotNull(message = "Policy type is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "policy_type_id", nullable = false)
    private PolicyType policyType;

    @NotNull(message = "Coverage amount is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Coverage amount must be positive")
    @Column(name = "coverage_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal coverageAmount;

    @NotNull(message = "Premium amount is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Premium amount must be positive")
    @Column(name = "premium_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal premiumAmount;

    @Column(name = "benefits", columnDefinition = "TEXT")
    private String benefits;

    @Column(name = "exclusions", columnDefinition = "TEXT")
    private String exclusions;

    @Min(value = 0, message = "Waiting period days cannot be negative")
    @Column(name = "waiting_period_days")
    private int waitingPeriodDays;

    @Column(name = "claim_process", columnDefinition = "TEXT")
    private String claimProcess;

    @Column(name = "documents_required", columnDefinition = "TEXT")
    private String documentsRequired;

    @Column(name = "eligibility", columnDefinition = "TEXT")
    private String eligibility;

    /** Risk classification assigned by AI underwriting engine: LOW, MEDIUM, or HIGH */
    @Column(name = "risk_category", length = 10)
    private String riskCategory;

    @Min(value = 1, message = "Duration must be at least 1 month")
    @Column(name = "duration_months", nullable = false)
    private int durationMonths;

    @Builder.Default
    @Column(name = "active", nullable = false)
    private boolean active = true;

    /**
     * Riders that can be added to this policy template at purchase time.
     * Admin-configurable via the rate-config panel.
     */
    @Builder.Default
    @ManyToMany
    @JoinTable(
            name = "policy_riders",
            joinColumns = @JoinColumn(name = "policy_id"),
            inverseJoinColumns = @JoinColumn(name = "rider_id")
    )
    private List<Rider> availableRiders = new ArrayList<>();
}
